language: php
php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'

before_script:
  - if find . -name "*.php" -exec php -l {} 2>&1 \; | grep -i "syntax error"; then exit 1; fi

notifications:
  email:
    - troman@cacti.net
